### ISSUE TITLE
reach router vs react router

### ISSUE THREAD

**Issue by saraf22** [ganeshf22/f22-react-boilerplate#10]

**Comment by ganeshf22** [comment]
@saraf22 https://reacttraining.com/blog/reach-react-router-future/

**Comment by saraf22** [comment]
so what is the new one's name??

**Comment by ganeshf22** [comment]
@saraf22 There is no new one, react router will be one left after the merge between two repos. But its api will be similar to @reach/router. So we are planning to use that
